In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [5]:
df=pd.read_csv("drug200.csv")

In [6]:
df.head(5)

,Age,Sex,BP,Cholesterol,Na_to_K,Drug
0,23,F,HIGH,HIGH,25.355,DrugY
1,47,M,LOW,HIGH,13.093,drugC
2,47,M,LOW,HIGH,10.114,drugC
3,28,F,NORMAL,HIGH,7.798,drugX
4,61,F,LOW,HIGH,18.043,DrugY


In [7]:
#Encoding the categorical values to numericals
le=LabelEncoder()
df["Sex"]=le.fit_transform(df["Sex"])
df["BP"]=le.fit_transform(df["BP"])
df["Cholesterol"]=le.fit_transform(df["Cholesterol"])
df["Drug"]=le.fit_transform(df["Drug"])

In [8]:
df.head()

,Age,Sex,BP,Cholesterol,Na_to_K,Drug
0,23,0,0,0,25.355,0
1,47,1,1,0,13.093,3
2,47,1,1,0,10.114,3
3,28,0,2,0,7.798,4
4,61,0,1,0,18.043,0


In [9]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [17]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [18]:
X=df.drop("Drug",axis=1)
y=df["Drug"]

In [19]:
from sklearn.preprocessing import StandardScaler

In [21]:
ss=StandardScaler()
X=ss.fit_transform(X)

In [22]:
print(X)

[[-1.29159102 -1.040833   -1.11016894 -0.97043679  1.28652212]
 [ 0.16269866  0.96076892  0.10979693 -0.97043679 -0.4151454 ]
 [ 0.16269866  0.96076892  0.10979693 -0.97043679 -0.82855818]
 [-0.988614   -1.040833    1.32976279 -0.97043679 -1.14996267]
 [ 1.0110343  -1.040833    0.10979693 -0.97043679  0.27179427]
 [-1.35218642 -1.040833    1.32976279 -0.97043679 -1.03769314]
 [ 0.28388946 -1.040833    1.32976279 -0.97043679  0.02643885]
 [-0.20087376  0.96076892  0.10979693 -0.97043679 -0.70046821]
 [ 0.9504389   0.96076892  1.32976279 -0.97043679 -0.12676951]
 [-0.07968296  0.96076892  0.10979693  1.03046381  0.45567206]
 [ 0.16269866 -1.040833    0.10979693 -0.97043679 -0.59916196]
 [-0.62504158 -1.040833   -1.11016894  1.03046381  0.43221897]
 [-0.07968296  0.96076892  0.10979693 -0.97043679 -0.09832049]
 [ 1.79877454 -1.040833    0.10979693 -0.97043679  0.674105  ]
 [ 0.34448487 -1.040833    1.32976279 -0.97043679 -0.46926791]
 [-1.71575884 -1.040833   -1.11016894  1.03046381 -0.07

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
model=